version: '3.8'

volumes:
  db_value:

services:

  db:
    image: postgres
    volumes:
      - db_value:/var/lib/postgresql/data/

  backend:
    build: ../backend
    volumes:
      - ./app:/usr/src/app
    environment:
      - DATABASE_HOSTNAME=db
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/usr/src/app
      - db_value:/var/lib/postgresql/data/
    depends_on:
      - backend
